name: "Build Debian Live Minimal ISO"

on:
  push:
    branches: [arm64-dev]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

jobs:
  build:
    name: "Build"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          # - os: ubuntu-22.04
          #   arch: amd64
          - os: ubuntu-22.04-arm
            arch: arm64

    steps:
      - name: "Checking out git repository"
        uses: actions/checkout@v2

      - name: "Build Image"
        run: |
          ./build.sh

