name: "Build Debian Live Minimal ISO"

on:
  push:
    branches: [arm64-dev]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'

jobs:
  build:
    name: "Build"
    runs-on: "ubuntu-20.04-arm"

    steps:
      - name: "Checking out git repository"
        uses: actions/checkout@v2

      - name: "Build Image"
        run: |
          ./build.sh

